version: '3'

services:
  simple-blog:
    build: .
    container_name: simple-blog-app
    ports:
      - "8080:80"
    restart: always
    environment:
      - NODE_ENV=production
    # 可选：挂载自定义配置或数据
    # volumes:
    #   - ./custom-config:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s